### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by 1233Ao** [Under-estimate/McMotd#13]
21:45:05 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  21:45:05 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.5 (arch: 64)
  21:45:05 [INFO] https://github.com/iTXTech/mirai-console-loader
  21:45:05 [INFO] This program is licensed under GNU AGPL v3
  21:45:05 [INFO] Mirai Hibernate Plugin Announcement:
从 2.3.0 版本开始 使用 Hibernate 6.0, 需要一起升级 Pixiv Helper 到 2.0
 如果需要继续使用 Pixiv Helper 1，请使用 2.2.5
  21:45:05 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  21:45:05 [INFO] Verifying "net.mamoe:mirai-console" v2.13.2
  21:45:06 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.2
  21:45:06 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.2
  21:45:07 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  21:45:07 [INFO] Verifying "xyz.cssxsh.mirai:mirai-hibernate-plugin" v2.5.0
2022-12-19 21:45:08 I/main: Starting mirai-console...
2022-12-19 21:45:08 I/main:

==================================[ Mirai consosle 2.13.2 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓

2022-12-19 21:45:08 I/main: Backend: version 2.13.2, built on 2022-12-05 01:50:53.
2022-12-19 21:45:08 I/main: Frontend Terminal: version 2.13.2, provided by Mamoe Technologies
2022-12-19 21:45:08 I/main: Welcome to visit https://mirai.mamoe.net/
2022-12-19 21:45:08 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-12-19 21:45:08 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-19 21:45:08 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin BlomeSummer v1.2
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin Minecraft MOTD Fetcher v1.1.11
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2
2022-12-19 21:45:09 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-12-19 21:45:09 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-12-19 21:45:09 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.4
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin HRobot v3.4
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin WeatherForecastPlugin v1.0.0
2022-12-19 21:45:09 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2022-12-19 21:45:09 I/mirai-hibernate-plugin: Driver: org.h2.Driver Version 2.1
2022-12-19 21:45:10 I/mirai-hibernate-plugin: Driver: com.mysql.cj.jdbc.Driver Version 8.0
2022-12-19 21:45:10 I/mirai-hibernate-plugin: Driver: org.postgresql.Driver Version 42.5
2022-12-19 21:45:10 I/mirai-hibernate-plugin: Driver: org.sqlite.JDBC Version 3.39
2022-12-19 21:45:10 I/plugin: Successfully loaded plugin mirai-hibernate-plugin v2.5.0
2022-12-19 21:45:10 I/plugin: Successfully loaded plugin mirai-hibernate-http v1.0.0
2022-12-19 21:45:10 I/plugin: Successfully loaded plugin HuYanSession v2.2.6
2022-12-19 21:45:10 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-12-19 21:45:10 I/BlomeSummer: Biome Summer 已加载
2022-12-19 21:45:10 I/BlomeSummer: 此插件只做学习使用
2022-12-19 21:45:10 I/Minecraft MOTD Fetcher: McMotd is loading
2022-12-19 21:45:10 W/Minecraft MOTD Fetcher: 找不到指定的字体 : Microsoft YaHei，您可以在mcmotd.yml中修改字体名称
2022-12-19 21:45:10 I/Minecraft MOTD Fetcher: 检测到可用的字体列表: Bahnschrift Bold,Bahnschrift Bold Condensed,Bahnschrift Bold SemiCondensed,Bahnschrift Condensed,Bahnschrift Light,Bahnschrift Light Condensed,Bahnschrift Light SemiCondensed,Bahnschrift Regular,Bahnschrift SemiBold,Bahnschrift SemiBold Condensed,Bahnschrift SemiBold SemiCondensed,Bahnschrift SemiCondensed,Bahnschrift SemiLight,Bahnschrift SemiLight Condensed,Bahnschrift SemiLight SemiCondensed,Cascadia Code Bold,Cascadia Code Bold Italic,Cascadia Code ExtraLight,Cascadia Code ExtraLight Italic,Cascadia Code Italic,Cascadia Code Light,Cascadia Code Light Italic,Cascadia Code Regular,Cascadia Code SemiBold,Cascadia Code SemiBold Italic,Cascadia Code SemiLight,Cascadia Code SemiLight Italic,Cascadia Mono Bold,Cascadia Mono Bold Italic,Cascadia Mono ExtraLight,Cascadia Mono ExtraLight Italic,Cascadia Mono Italic,Cascadia Mono Light,Cascadia Mono Light Italic,Cascadia Mono Regular,Cascadia Mono SemiBold,Cascadia Mono SemiBold Italic,Cascadia Mono SemiLight,Cascadia Mono SemiLight Italic,Dialog.bold,Dialog.bolditalic,Dialog.italic,Dialog.plain,DialogInput.bold,DialogInput.bolditalic,DialogInput.italic,DialogInput.plain,MS Gothic,MS PGothic,MS UI Gothic,Microsoft JhengHei,Microsoft JhengHei Bold,Microsoft JhengHei Light,Microsoft JhengHei UI,Microsoft JhengHei UI Bold,Microsoft JhengHei UI Light,Microsoft YaHei UI Light,Microsoft Yahei UI,Microsoft Yahei UI Bold,Monospaced.bold,Monospaced.bolditalic,Monospaced.italic,Monospaced.plain,NSimSun,SansSerif.bold,SansSerif.bolditalic,SansSerif.italic,SansSerif.plain,Segoe UI Variable Display,Segoe UI Variable Display Bold,Segoe UI Variable Display Light,Segoe UI Variable Display Semibold,Segoe UI Variable Display Semilight,Segoe UI Variable Small,Segoe UI Variable Small Bold,Segoe UI Variable Small Light,Segoe UI Variable Small Semibold,Segoe UI Variable Small Semilight,Segoe UI Variable Text,Segoe UI Variable Text Bold,Segoe UI Variable Text Light,Segoe UI Variable Text Semibold,Segoe UI Variable Text Semilight,Serif.bold,Serif.bolditalic,Serif.italic,Serif.plain,SimSun,Sitka Banner,Sitka Banner Bold,Sitka Banner Bold Italic,Sitka Banner Italic,Sitka Banner Semibold,Sitka Banner Semibold Italic,Sitka Display,Sitka Display Bold,Sitka Display Bold Italic,Sitka Display Italic,Sitka Display Semibold,Sitka Display Semibold Italic,Sitka Heading,Sitka Heading Bold,Sitka Heading Bold Italic,Sitka Heading Italic,Sitka Heading Semibold,Sitka Heading Semibold Italic,Sitka Small,Sitka Small Bold,Sitka Small Bold Italic,Sitka Small Italic,Sitka Small Semibold,Sitka Small Semibold Italic,Sitka Subheading,Sitka Subheading Bold,Sitka Subheading Bold Italic,Sitka Subheading Italic,Sitka Subheading Semibold,Sitka Subheading Semibold Italic,Sitka Text Bold,Sitka Text Bold Italic,Sitka Text Semibold,Sitka Text Semibold Italic,Yu Gothic Bold,Yu Gothic Light,Yu Gothic Medium,Yu Gothic Regular,Yu Gothic UI Bold,Yu Gothic UI Light,Yu Gothic UI Regular,Yu Gothic UI Semibold,Yu Gothic UI Semilight,仿宋,华文中宋,华文仿宋,华文宋体,华文彩云,华文新魏,华文楷体,华文琥珀,华文细黑,华文行楷,华文隶书,宋体,幼圆,微软雅黑,微软雅黑 Bold,微软雅黑 Light,新宋体,方正姚体,方正舒体,楷体,等线,等线 Bold,等线 Light,隶书,黑体
2022-12-19 21:45:10 W/Minecraft MOTD Fetcher: 正在使用第一个可用的字体: Bahnschrift Bold
2022-12-19 21:45:10 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-12-19 21:45:10 I/Mirai HTTP API: ********************************************************
2022-12-19 21:45:10 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-12-19 21:45:10 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-19 21:45:10 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-19 21:45:10 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2022-12-19 21:45:10 I/ws adapter: >>> [ws adapter] is listening at ws://localhost:8080
2022-12-19 21:45:10 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEY3XSCzS6X
2022-12-19 21:45:10 I/Mirai HTTP API: adaptors: [http,ws]
2022-12-19 21:45:10 I/Mirai HTTP API: ********************************************************
2022-12-19 21:45:10 I/stdout:         ,--,
2022-12-19 21:45:10 I/stdout:       ,--.'|,-.----.                                    ___
2022-12-19 21:45:10 I/stdout:    ,--,  | :\    /  \             ,---,               ,--.'|_
2022-12-19 21:45:10 I/stdout: ,---.'|  : ';   :    \   ,---.  ,---.'|      ,---.    |  | :,'
2022-12-19 21:45:10 I/stdout: |   | : _' ||   | .\ :  '   ,'\ |   | :     '   ,'\   :  : ' :
2022-12-19 21:45:10 I/stdout: :   : |.'  |.   : |: | /   /   |:   : :    /   /   |.;__,'  /
2022-12-19 21:45:10 I/stdout: |   ' '  ; :|   |  \ :.   ; ,. ::     |,-..   ; ,. :|  |   |
2022-12-19 21:45:10 I/stdout: '   |  .'. ||   : .  /'   | |: :|   : '  |'   | |: ::__,'| :
2022-12-19 21:45:10 I/stdout: |   | :  | ';   | |  \'   | .; :|   |  / :'   | .; :  '  : |__
2022-12-19 21:45:10 I/stdout: '   : |  : ;|   | ;\  \   :    |'   : |: ||   :    |  |  | '.'|
2022-12-19 21:45:10 I/stdout: |   | '  ,/ :   ' | \.'\   \  / |   | '/ : \   \  /   ;  :    ;
2022-12-19 21:45:10 I/stdout: ;   : ;--'  :   : :-'   `----'  |   :    |  `----'    |  ,   /
2022-12-19 21:45:10 I/stdout: |   ,/      |   |.'             /    \  /              ---`-'
2022-12-19 21:45:10 I/stdout: '---'       `---'               `-'----'                            v3.4
2022-12-19 21:45:10 I/HRobot: 正在初始化机器人配置
2022-12-19 21:45:10 I/HRobot: 配置初始化完成
2022-12-19 21:45:10 W/HRobot: Linked class org.slf4j.impl.StaticLoggerBinder in mcmotd-1.1.11.mirai.jar but plugin not depend on it.
2022-12-19 21:45:10 W/HRobot: Class loading logic may change in feature.
2022-12-19 21:45:10 I/HRobot: HRobot handlers and filters loading finished, total 17 handlers, 3 inspectors.
2022-12-19 21:45:10 E/HRobot: java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce of the current class, org/slf4j/LoggerFactory, and the class loader 'mcmotd-1.1.11.mirai.jar' @43c57161 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce, parent loader 'global-shared' @7b948f3e; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'mcmotd-1.1.11.mirai.jar' @43c57161, parent loader 'global-shared' @7b948f3e)
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce of the current class, org/slf4j/LoggerFactory, and the class loader 'mcmotd-1.1.11.mirai.jar' @43c57161 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce, parent loader 'global-shared' @7b948f3e; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'mcmotd-1.1.11.mirai.jar' @43c57161, parent loader 'global-shared' @7b948f3e)
        at plugin-3.4-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
        at plugin-3.4-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
        at plugin-3.4-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
        at plugin-3.4-SNAPSHOT.mirai.jar//org.quartz.impl.StdSchedulerFactory.<init>(StdSchedulerFactory.java:303)
        at plugin-3.4-SNAPSHOT.mirai.jar//org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1533)
        at plugin-3.4-SNAPSHOT.mirai.jar//com.happysnaker.cron.RobotCronJob.<clinit>(RobotCronJob.java:54)
        at plugin-3.4-SNAPSHOT.mirai.jar//com.happysnaker.starter.HRobotStarter.Start(HRobotStarter.java:71)
        at plugin-3.4-SNAPSHOT.mirai.jar//com.happysnaker.Main.onEnable(Main.java:25)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)

2022-12-19 21:45:10 I/WeatherForecastPlugin: Weather Forecast Plugin loaded!
2022-12-19 21:45:10 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2022-12-19 21:45:10 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2022-12-19 21:45:11 W/stderr: SLF4J: No SLF4J providers were found.
2022-12-19 21:45:11 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-19 21:45:11 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
2022-12-19 21:45:11 I/mirai-hibernate-plugin: Database jdbc:h2:file:./data/xyz.cssxsh.mirai.plugin.mirai-hibernate-plugin/hibernate.h2 by H2 JDBC Driver.
2022-12-19 21:45:11 I/mirai-hibernate-plugin: 如果要使用 mirai-hibernate-plugin 为 mirai-api-http 提供消息持久化, 请安装 https://github.com/cssxsh/mirai-hibernate-http
2022-12-19 21:45:11 I/HuYanSession: ===================HuYanSession2===================
2022-12-19 21:45:11 I/HuYanSession:     //    / /      \\    / /                   //   ) )

2022-12-19 21:45:11 I/HuYanSession:    //___ / /        \\  / /  ___       __     ((         ___      ___      ___     ( )  ___       __
2022-12-19 21:45:11 I/HuYanSession:   / ___   / //   / / \\/ / //   ) ) //   ) )    \\     //___) ) ((   ) ) ((   ) ) / / //   ) ) //   ) )
2022-12-19 21:45:11 I/HuYanSession:  //    / / //   / /   / / //   / / //   / /       ) ) //         \ \      \ \    / / //   / / //   / /
2022-12-19 21:45:11 I/HuYanSession: //    / / ((___( (   / / ((___( ( //   / / ((___ / / ((____   //   ) ) //   ) ) / / ((___/ / //   / /
2022-12-19 21:45:11 I/HuYanSession: HuYanSession2 当前版本: v2.2.6
2022-12-19 21:45:12 I/HuYanSession: H2数据库初始化成功!
2022-12-19 21:45:12 I/HuYanSession: 插件配置已加载！
2022-12-19 21:45:12 I/HuYanSession: 主人已设置:3031917948
2022-12-19 21:45:12 I/HuYanSession: 插件指令已加载！
2022-12-19 21:45:12 I/HuYanSession: 数据库群组信息初始化成功!
2022-12-19 21:45:12 I/HuYanSession: 多词条消息初始化成功!
2022-12-19 21:45:12 I/stdout: [2022-12-19 21:45:12] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
2022-12-19 21:45:12 I/HuYanSession: 定时器加载成功!
2022-12-19 21:45:12 I/HuYanSession: 群消息监听已注册！
2022-12-19 21:45:12 I/HuYanSession: 群动作监听已注册！
2022-12-19 21:45:12 I/HuYanSession: 壶言会话插件加载完成!
2022-12-19 21:45:12 I/HuYanSession: ===================HuYanSession2===================
2022-12-19 21:45:12 I/main: 10 plugin(s) enabled.
2022-12-19 21:45:12 I/main: Auto-login 2016401389, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2022-12-19 21:45:13 I/Bot.2016401389: Login successful
2022-12-19 21:45:13 I/Bot.2016401389: Saved account secrets to local cache for fast login.
2022-12-19 21:45:13 I/Bot.2016401389: Login successful.
2022-12-19 21:45:13 V/Bot.2016401389: Event: BotOnlineEvent(bot=Bot(2016401389))
2022-12-19 21:45:13 I/Bot.2016401389: Bot login successful.
2022-12-19 21:45:13 I/main: mirai-console started successfully.
2022-12-19 21:45:13 W/WeatherForecastPlugin: Linked class org.slf4j.impl.StaticLoggerBinder in mcmotd-1.1.11.mirai.jar but plugin not depend on it.
2022-12-19 21:45:13 W/WeatherForecastPlugin: Class loading logic may change in feature.
2022-12-19 21:45:13 W/Bot.2016401389: An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot 2016401389.EventDispatcher'
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'weather_forecast-2.0.0.mirai.jar' @71ed560f of the current class, org/slf4j/LoggerFactory, and the class loader 'mcmotd-1.1.11.mirai.jar' @43c57161 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'weather_forecast-2.0.0.mirai.jar' @71ed560f, parent loader 'global-shared' @7b948f3e; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'mcmotd-1.1.11.mirai.jar' @43c57161, parent loader 'global-shared' @7b948f3e)
        at weather_forecast-2.0.0.mirai.jar//org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
        at weather_forecast-2.0.0.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at weather_forecast-2.0.0.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at weather_forecast-2.0.0.mirai.jar//org.quartz.impl.StdSchedulerFactory.<init>(StdSchedulerFactory.java:303)
        at weather_forecast-2.0.0.mirai.jar//pers.gaylong9.forecast.Forecast.forecast(Forecast.java:24)
        at weather_forecast-2.0.0.mirai.jar//pers.gaylong9.WeatherForecastPlugin.lambda$onEnable$0(WeatherForecastPlugin.java:55)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:626)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:626)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Under-estimate** [comment]
> java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader **`'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce`** of the current class, org/slf4j/LoggerFactory, and the class loader **`'mcmotd-1.1.11.mirai.jar' @43c57161`** for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'plugin-3.4-SNAPSHOT.mirai.jar' @4cb702ce, parent loader 'global-shared' @7b948f3e; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'mcmotd-1.1.11.mirai.jar' @43c57161, parent loader 'global-shared' @7b948f3e)

以上问题似乎是`McMotd`和`HRobot`插件都引入了`slf4j`依赖所导致的，我在[最新Release](https://github.com/Under-estimate/McMotd/releases/tag/v1.1.12)里移除了`slf4j`依赖，你可以试一下看有没有解决
